### ISSUE TITLE
Is there a reliable method to get the link to the restaurant?

### ISSUE THREAD

**Issue by Abstiens** [TakeawayAPI/node-takeaway#2]
Hey there,

awesome work so far and great to see that you are still working on this project.

Is there are reliable method to get the restaurant link? Right now, i am kinda "guessing" the link by clearing the name of the restaurant and then trying some variations. This only works in 99% of the cases, but sometimes i end up in a completely different restaurant (same name, different city => different restaurant). 

Is there something i am missing?

**Comment by DanielHuisman** [comment]
This library uses the API for the Android app. In the app there is no need or way to link to the restaurant page. The only other way I can think of to determine the URL would be to make a request to the normal site using the same postal code, parsing the HTML and finding the restaurant by ID in the parsed data.
