### ISSUE TITLE
Can't use `require`

### ISSUE THREAD

**Issue by alFReD-NSH** [TakeawayAPI/node-takeaway#5]
Apparently doing a `require('takeaway')` returns an empty object. This is because https://github.com/TakeawayAPI/node-takeaway/blob/master/index.js is not exporting anything.

**Comment by DanielHuisman** [comment]
It should be fixed in the latest version https://github.com/TakeawayAPI/node-takeaway/commit/c1f626f69034950b196ab777d502b71f7d10e02e
